language: go
cache:
  directories:
    - ${GOPATH}/src/github.com
    - ${GOPATH}/src/golang.org
go: 1.6
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - go get -v github.com/h12w/gosweep
  - go get -v github.com/Masterminds/glide
  - glide install

script:
  - go test -v ./...

after_success:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
