language: go
cache:
  directories:
    - ${GOPATH}/src/github.com/${TRAVIS_REPO_SLUG}/vendor
    - ${GOPATH}/src/github.com/client9/misspell
    - ${GOPATH}/src/github.com/fzipp/gocyclo
    - ${GOPATH}/src/github.com/h12w
    - ${GOPATH}/src/github.com/Masterminds    
    - ${GOPATH}/src/github.com/mattn
    - ${GOPATH}/src/github.com/pborman
go:
  - tip
  - 1.8
  - 1.7
  - 1.6
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - go get -v -u github.com/client9/misspell/cmd/misspell
  - go get -v -u github.com/fzipp/gocyclo
  - go get -v -u github.com/h12w/gosweep
  - go get -v -u github.com/mattn/goveralls
  - go get -v -u github.com/Masterminds/glide
  - glide install

script:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh
