language: go
go: 1.4
sudo: false

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/crypto/bcrypt

  - go get github.com/stretchr/testify
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -cover ./...
  - golint ./...

