language: go
cache:
  directories:
    - ${GOPATH}/src/github.com
    - ${GOPATH}/src/golang.org
go: 1.6
sudo: false

env:
    CI_SERVICE=travis-ci

install:
  - cat requirements.txt test-requirements.txt | xargs -I @@ -P 4 go get @@

script:
  - go test -v ./...

after_success:
  - bash ${GOPATH}/src/github.com/h12w/gosweep/gosweep.sh

